# Generated by Django 5.1.3 on 2024-11-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CotacaoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('codein', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('varBid', models.FloatField()),
                ('pctChange', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('create_date', models.DateTimeField()),
            ],
        ),
    ]
